---
- name: install EPEL repo
  yum:
    name: "{{ epel_repo_url }}"
    state: present
  register: result
  until: '"failed" not in result'
  retries: 5
  delay: 10

- name: import EPEL key
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present

- name: Install fail2ban.
  yum: name=fail2ban state=present enablerepo=epel
