---
# Fail2Ban
- include: fail2ban-RedHat.yml
  when: ansible_os_family == 'RedHat'
  become: yes

- include: fail2ban-Debian.yml
  when: ansible_os_family == 'Debian'
  become: yes

- name: Ensure fail2ban is running and enabled on boot.
  service: name=fail2ban state=started enabled=yes
  become: yes

# Autoupdate
- include: autoupdate-RedHat.yml
  when: ansible_os_family == 'RedHat' and security_autoupdate_enabled
  become: yes

- include: autoupdate-Debian.yml
  when: ansible_os_family == 'Debian' and security_autoupdate_enabled
  become: yes

# Random CIS stuff
- name: CIS 1.4.1 Set User/Group Owner on bootloader config
  file: path=/boot/grub/grub.cfg follow=yes owner=root group=root mode=0400
  become: yes
  when: ansible_os_family == 'Debian'

- name: CIS 1.5.1 Restrict Core Dumps (Scored) - using sysctl
  sysctl: name=fs.suid_dumpable value=0 ignoreerrors=yes sysctl_set=yes reload=yes state=present
  become: yes

- name: 5.2.4 Disable SSH X11 Forwarding (Scored)
  lineinfile: dest=/etc/ssh/sshd_config regexp="^X11Forwarding" line="X11Forwarding no" state=present
  notify: restart ssh
  become: yes
  
- name: 5.2.5 Set SSH MaxAuthTries to 4 or Less (Scored)
  lineinfile: dest=/etc/ssh/sshd_config regexp="^MaxAuthTries" line="MaxAuthTries 4" state=present
  notify: restart ssh
  become: yes

- include: pam-Debian.yml
  when: ansible_os_family == 'Debian'
  become: yes

- name: Remove unnecessary suid/sgid binaries (nixu)
  apt:
    name: "{{item}}"
    state: absent
  when: ansible_os_family == 'Debian'
  become: yes
  with_items:
    - ntfs-3g
    - eject

- include: coredumps.yml
  become: yes

- include: network-hardening.yml
  become: yes

- include: logging.yml
  become: yes

- include: ufw-Debian.yml
  when: ansible_os_family == 'Debian'
  become: yes