  - name: 3.1.2 Ensure packet redirect sending is disabled (Scored)
    sysctl:
      name: net.ipv4.conf.all.send_redirects
      value: 0
      state: present

  - name: 3.2.1 Ensure source routed packets are not accepted (Scored)
    sysctl:
      name: net.ipv4.conf.all.accept_source_route
      value: 0
      state: present

  - name: 3.2.2 Ensure ICMP redirects are not accepted (Scored)
    sysctl:
      name: net.ipv4.conf.all.accept_redirects
      value: 0
      state: present

  - name: 3.2.3 Ensure secure ICMP redirects are not accepted (Scored)
    sysctl:
      name: net.ipv4.conf.all.secure_redirects
      value: 0
      state: present

  - name: 3.2.4 Ensure suspicious packets are logged (Scored)
    sysctl:
      name: net.ipv4.conf.all.log_martians
      value: 1
      state: present

  - name: 3.2.5 Ensure broadcast ICMP requests are ignored (Scored)
    sysctl:
      name: net.ipv4.icmp_echo_ignore_broadcasts
      value: 1
      state: present

  - name: 3.2.6 Ensure bogus ICMP responses are ignored (Scored)
    sysctl:
      name: net.ipv4.icmp_ignore_bogus_error_responses
      value: 1
      state: present

  - name: 3.2.7 Ensure Reverse Path Filtering is enabled (Scored)
    sysctl:
      name: net.ipv4.conf.all.rp_filter
      value: 1
      state: present

  - name: 3.2.8 Ensure TCP SYN Cookies is enabled (Scored)
    sysctl:
      name: net.ipv4.tcp_syncookies
      value: 1
      state: present

  - name: 3.3.1 Ensure IPv6 router advertisements are not accepted (Not Scored)
    sysctl:
      name: net.ipv6.conf.all.accept_ra
      value: 0
      state: present

  - name: 3.3.2 Ensure IPv6 redirects are not accepted (Not Scored)
    sysctl:
      name: net.ipv6.conf.default.accept_redirects
      value: 0
      state: present

  - name: 3.3.3 Ensure IPv6 is disabled (Not Scored)
    sysctl:
      name: "{{ item }}"
      value: 1
      state: present
    with_items:
      - net.ipv6.conf.all.disable_ipv6
      - net.ipv6.conf.default.disable_ipv6
      - net.ipv6.conf.lo.disable_ipv6
    when: disable_ipv6 == True
