- name: 1.1.2 Ensure separate partition exists for /tmp (Scored)
  command: grep '\s/tmp\s' /etc/fstab
  register: tmp_partition
  failed_when: tmp_partition.rc == 1
  changed_when: False
  ignore_errors: True

- apt:
    name: python-pip
    state: present
  when: tmp_partition.rc == 0

- name: install dependencies for mountopts-module
  pip:
    name: fstab
  when: tmp_partition.rc == 0

- mountopts:
    name: /tmp
    option: nodev
    state: present
  when: tmp_partition.rc == 0

- shell: mount | grep /tmp|grep nodev
  register: mount_tmp_output
  failed_when: False
  ignore_errors: True

- name: 1.1.3 Ensure nodev option set on /tmp partition (Scored)
  command: mount -o remount,nodev /tmp
  ignore_errors: True
  when: tmp_partition.rc == 0 and mount_tmp_output.rc != 0

- apt:
    name: python-pip
    state: present
  when: tmp_partition.rc == 0

- name: install dependencies for mountopts-module
  pip:
    name: fstab
  when: tmp_partition.rc == 0

- mountopts:
    name: /tmp
    option: nosuid
    state: present
  when: tmp_partition.rc == 0

- shell: mount | grep /tmp|grep nosuid
  register: mount_tmp_output
  failed_when: false
  ignore_errors: True
  changed_when: False

- name: 1.1.4 Ensure nosuid option set on /tmp partition (Scored)
  command: mount -o remount,nosuid /tmp
  ignore_errors: True
  when: tmp_partition.rc == 0 and mount_tmp_output.rc != 0

- name: 1.1.5 Ensure separate partition exists for /var (Scored)
  command: grep '\s/var\s' /etc/fstab
  register: var_partition
  failed_when: var_partition.rc == 1
  changed_when: False
  ignore_errors: True

- apt:
    name: python-pip
    state: present
  when: var_partition.rc == 0

- name: install dependencies for mountopts-module
  pip:
    name: fstab
  when: var_partition.rc == 0

- mountopts:
    name: /var
    option: nosuid
    state: present
  when: var_partition.rc == 0

- mountopts:
    name: /var
    option: noexec
    state: present
  when: var_partition.rc == 0

- mountopts:
    name: /var
    option: nodev
    state: present
  when: var_partition.rc == 0

- name: 1.1.6 Ensure separate partition exists for /var/tmp (Scored)
  command: grep '\s/var/tmp\s' /etc/fstab
  register: var_tmp_partition
  failed_when: var_tmp_partition.rc == 1
  changed_when: False
  ignore_errors: True

- apt:
    name: python-pip
    state: present
  when: var_tmp_partition.rc == 0

- name: install dependencies for mountopts-module
  pip:
    name: fstab
  when: var_tmp_partition.rc == 0

- mountopts:
    name: /var/tmp
    option: nodev
    state: present
  when: var_tmp_partition.rc == 0

- shell: mount | grep /var/tmp|grep nodev
  register: mount_var_tmp_output
  failed_when: false
  ignore_errors: True
  changed_when: False

- name: 1.1.7 Ensure nodev option set on /var/tmp partition (Scored)
  command: mount -o remount,nodev /var/tmp
  ignore_errors: True
  when: var_tmp_partition.rc == 0 and mount_var_tmp_output.rc != 0

- apt:
    name: python-pip
    state: present
  when: var_tmp_partition.rc == 0

- name: install dependencies for mountopts-module
  pip:
    name: fstab
  when: var_tmp_partition.rc == 0

- mountopts:
    name: /var/tmp
    option: nosuid
    state: present
  when: var_tmp_partition.rc == 0

- shell: mount | grep /var/tmp|grep nosuid
  register: mount_var_tmp_output
  failed_when: false
  ignore_errors: True
  changed_when: False

- name: 1.1.8 Ensure nosuid option set on /var/tmp partition (Scored)
  command: mount -o remount,nosuid /var/tmp
  ignore_errors: True
  when: var_tmp_partition.rc == 0 and mount_var_tmp_output.rc != 0

- apt:
    name: python-pip
    state: present
  when: var_tmp_partition.rc == 0

- name: install dependencies for mountopts-module
  pip:
    name: fstab
  when: var_tmp_partition.rc == 0

- mountopts:
    name: /var/tmp
    option: noexec
    state: present
  when: var_tmp_partition.rc == 0

- shell: mount | grep /var/tmp|grep noexec
  register: mount_var_tmp_output
  failed_when: false
  ignore_errors: True
  changed_when: False

- name: 1.1.9 Ensure noexec option set on /var/tmp partition (Scored)
  command: mount -o remount,noexec /var/tmp
  ignore_errors: True
  when: var_tmp_partition.rc == 0 and mount_var_tmp_output.rc != 0

- name: 1.1.10 Ensure separate partition exists for /var/log (Scored)
  command: grep '\s/var/log\s' /etc/fstab
  register: var_log_partition
  failed_when: var_log_partition.rc == 1
  changed_when: False
  ignore_errors: True

- apt:
    name: python-pip
    state: present
  when: var_log_partition.rc == 0

- name: install dependencies for mountopts-module
  pip:
    name: fstab
  when: var_log_partition.rc == 0

- mountopts:
    name: /var/log
    option: noexec
    state: present
  when: var_log_partition.rc == 0

- mountopts:
    name: /var/log
    option: nodev
    state: present
  when: var_log_partition.rc == 0

- mountopts:
    name: /var/log
    option: nosuid
    state: present
  when: var_log_partition.rc == 0

- name: 1.1.11 Ensure separate partition exists for /var/log/audit (Scored)
  command: grep '\s/var/log/audit\s' /etc/fstab
  register: var_log_audit_partition
  failed_when: var_log_audit_partition.rc == 1
  changed_when: False
  ignore_errors: True

- apt:
    name: python-pip
    state: present
  when: var_log_audit_partition.rc == 0

- name: install dependencies for mountopts-module
  pip:
    name: fstab
  when: var_log_audit_partition.rc == 0

- mountopts:
    name: /var/log/audit
    option: noexec
    state: present
  when: var_log_audit_partition.rc == 0

- mountopts:
    name: /var/log/audit
    option: nodev
    state: present
  when: var_log_audit_partition.rc == 0

- mountopts:
    name: /var/log/audit
    option: nosuid
    state: present
  when: var_log_audit_partition.rc == 0

- name: 1.1.12 Ensure separate partition exists for /home (Scored)
  command: grep '\s/home\s' /etc/fstab
  register: home_partition
  failed_when: home_partition.rc == 1
  changed_when: False
  ignore_errors: True

- apt:
    name: python-pip
    state: present
  when: home_partition.rc == 0

- name: install dependencies for mountopts-module
  pip:
    name: fstab
  when: home_partition.rc == 0

- mountopts:
    name: /home
    option: nodev
    state: present
  when: home_partition.rc == 0

- shell: mount | grep /home|grep nodev
  register: mount_home_output
  failed_when: false
  ignore_errors: True
  changed_when: False

- name: 1.1.13 Ensure nodev option set on /home partition (Scored)
  command: mount -o remount,nodev /home
  ignore_errors: True
  when: home_partition.rc == 0 and mount_home_output.rc == 1
