- name: 2.1 Create Separate Partition for /tmp (Scored)
  command: grep '\s/tmp\s' /etc/fstab
  register: tmp_partition
  when: partitioning == True
  failed_when: tmp_partition.rc == 1
  changed_when: False
  ignore_errors: True

- name: 2.2 - 4 Set nodev, nosuid, noexec Options for /tmp Partition (Scored)
  mount: name="/tmp" src="/tmp" state="mounted" opts="defaults,nodev,nosuid,noexec" fstype=ext4
  when: partitioning == True

- name: 2.5 Create Separate Partition for /var (Scored)
  command: grep '\s/var\s' /etc/fstab
  when: partitioning == True
  register: var_partition
  failed_when: var_partition.rc == 1
  changed_when: False
  ignore_errors: True

- name: 2.6 Bind Mount the /var/tmp directory to /tmp (Scored)
  mount: name="/var/tmp" src="/tmp" opts=bind state=mounted fstype=ext4
  when: partitioning == True

- name: 2.7 Create Separate Partition for /var/log (Scored)
  command: grep '\s/var\/log\s' /etc/fstab
  when: partitioning == True
  register: var_log_partition
  failed_when: var_log_partition.rc == 1
  changed_when: False
  ignore_errors: True

- name: 2.8 Create Separate Partition for /var/log/audit (Scored)
  command: grep '\s/var\/log\/audit\s' /etc/fstab
  when: partitioning == True
  register: var_log_audit_partition
  failed_when: var_log_audit_partition.rc == 1
  changed_when: False
  ignore_errors: True

- name: 2.9 Create Separate Partition for /home (Scored)
  command: grep '\s/home\s' /etc/fstab
  when: partitioning == True
  register: home_partition
  failed_when: home_partition.rc == 1
  changed_when: False
  ignore_errors: True

- name: 2.10 Add nodev Option to /home (Scored)
  mount: name="/home" src="/home" state=mounted opts=defaults,nodev fstype="ext4"
  when: partitioning == True

