- name: install ufw
  apt: name=ufw state=present
  become: yes

- name: set up ufw port rules
  ufw: 
    rule: allow
    port: "{{item}}"
    proto: tcp
  with_items: "{{ufw_allow_tcp_ports}}"
  become: yes
  notify:
    - reload ufw

- ufw:
    rule: allow
    src: "{{item}}"
  with_items: "{{ufw_allow_networks}}"
  become: yes
  notify:
    - reload ufw

- ufw:
    direction: incoming
    default: deny
  become: yes
  notify:
    - reload ufw

- ufw:
    logging: on
  become: yes
  notify:
    - reload ufw

- ufw:
    state: enabled
  become: yes
